[project]
name = "msa-app"
version = "1.0.0"
description = "ðŸŒ A web-based interface for running Multiple Sequence Alignment (MSA) using A-Star and PA-Star algorithms."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.2",
    "werkzeug>=3.1.5",
]
